name = "studio-digital"
compatibility_date = "2026-07-01"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "studio-digital"
database_id = "18a39ae2-82dd-4e41-95a8-ed1ad0767797"

[[r2_buckets]]
binding = "PHOTOS"
bucket_name = "studio-digital-photos"
